version: '3.9'
services:
  db:
    container_name: clean-db
    image: postgres:15.2-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env
  api:
    container_name: clean-api
    build: .
    tty: true
    volumes:
      - .:/app/src
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    command: air

  adminer:
    container_name: clean-adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata: