pkgname = "model"
output = "pkg/domain/model"
wipe = true
no-tests = true
add-global-variants = true
add-soft-deletes = true

[psql]
dbname = "test"
host = "localhost"
port = "5432"
user = "user"
pass = "password"
sslmode = "disable"
blacklist = ["schema_migrations"]