// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Follows string
	Likes   string
	Posts   string
	Users   string
}{
	Follows: "follows",
	Likes:   "likes",
	Posts:   "posts",
	Users:   "users",
}
